# This workflow builds Python wheels for Windows using cibuildwheel
# See: https://cibuildwheel.readthedocs.io/en/stable/

name: Build wheels (Windows)

on:
  release:
    types: [ published ]

jobs:
  build_wheels:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Build wheels with cibuildwheel
      uses: pypa/cibuildwheel@v2.23.3
      with:
        output-dir: wheelhouse
      env:
        CIBW_BUILD: cp39-win_amd64 cp310-win_amd64 cp311-win_amd64 cp312-win_amd64
    - name: Upload wheels to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: wheelhouse/*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
