# This workflow builds Python wheels for Windows using cibuildwheel
# See: https://cibuildwheel.readthedocs.io/en/stable/

name: Build wheels (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_wheels:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install cibuildwheel
      run: pip install cibuildwheel
    - name: Build wheels
      run: cibuildwheel --platform windows
      env:
        CIBW_BUILD: cp3*-win_amd64
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: wheelhouse/*.whl
